name: x2_fwupdate
description: Manage X2 firmware
publish_to: 'none'

environment:
  sdk: '>=2.17.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_libserialport: ^0.3.0
  flutter_riverpod: ^2.3.6
  loading_animation_widget: ^1.2.0+4
  process_run: ^0.13.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/aon2-logo-white.png
