name: x2_fwupdate
description: Manage X2 firmware
publish_to: 'none'

environment:
  sdk: '>=2.17.0'

dependencies:

  flutter:
    sdk: flutter
  quick_usb: 0.3.1
  flutter_libserialport: ^0.2.3
  flutter_riverpod: ^2.3.6
  loading_animation_widget: ^1.2.0+4
  process_run: ^0.13.1
  url_launcher: ^6.1.12
  http: ^1.1.0
  background_downloader: ^7.8.1
  path_provider: ^2.0.15

flutter:
  uses-material-design: true
  assets:
    - assets/images/aon2-logo-white.png
