name: flutter_libserialport_example
description: Demonstrates how to use the flutter_libserialport plugin.
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_libserialport: ^0.3.0

flutter:
  uses-material-design: true
